//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWinFormApp.LemonWayWebServiceSoap")]
    public interface LemonWayWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fibonacci", ReplyAction="*")]
        int Fibonacci(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fibonacci", ReplyAction="*")]
        System.Threading.Tasks.Task<int> FibonacciAsync(int n);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément xmlString de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJson", ReplyAction="*")]
        LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonResponse XmlToJson(LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJson", ReplyAction="*")]
        System.Threading.Tasks.Task<LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonResponse> XmlToJsonAsync(LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJson", Namespace="http://tempuri.org/", Order=0)]
        public LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequestBody Body;
        
        public XmlToJsonRequest() {
        }
        
        public XmlToJsonRequest(LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlToJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlString;
        
        public XmlToJsonRequestBody() {
        }
        
        public XmlToJsonRequestBody(string xmlString) {
            this.xmlString = xmlString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonResponseBody Body;
        
        public XmlToJsonResponse() {
        }
        
        public XmlToJsonResponse(LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlToJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonResult;
        
        public XmlToJsonResponseBody() {
        }
        
        public XmlToJsonResponseBody(string XmlToJsonResult) {
            this.XmlToJsonResult = XmlToJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LemonWayWebServiceSoapChannel : LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.LemonWayWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LemonWayWebServiceSoapClient : System.ServiceModel.ClientBase<LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.LemonWayWebServiceSoap>, LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.LemonWayWebServiceSoap {
        
        public LemonWayWebServiceSoapClient() {
        }
        
        public LemonWayWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LemonWayWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LemonWayWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Fibonacci(int n) {
            return base.Channel.Fibonacci(n);
        }
        
        public System.Threading.Tasks.Task<int> FibonacciAsync(int n) {
            return base.Channel.FibonacciAsync(n);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonResponse LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.LemonWayWebServiceSoap.XmlToJson(LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequest request) {
            return base.Channel.XmlToJson(request);
        }
        
        public string XmlToJson(string xmlString) {
            LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequest inValue = new LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequest();
            inValue.Body = new LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequestBody();
            inValue.Body.xmlString = xmlString;
            LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonResponse retVal = ((LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.LemonWayWebServiceSoap)(this)).XmlToJson(inValue);
            return retVal.Body.XmlToJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonResponse> LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.LemonWayWebServiceSoap.XmlToJsonAsync(LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequest request) {
            return base.Channel.XmlToJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonResponse> XmlToJsonAsync(string xmlString) {
            LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequest inValue = new LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequest();
            inValue.Body = new LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.XmlToJsonRequestBody();
            inValue.Body.xmlString = xmlString;
            return ((LemonWay.ConsumeWS.WinFormApp.ServiceReferenceWinFormApp.LemonWayWebServiceSoap)(this)).XmlToJsonAsync(inValue);
        }
    }
}
